//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyDeTai.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Administrator
    {
        public string adminId { get; set; }
        public string adminName { get; set; }
        public bool gender { get; set; }
        public System.DateTime birth { get; set; }
        public string email { get; set; }
        public string phone { get; set; }
        public string degree { get; set; }
        public string signUpId { get; set; }
        public string examinationBoardId { get; set; }
    
        public virtual ExaminationBoard ExaminationBoard { get; set; }
        public virtual SignUp SignUp { get; set; }
    }
}
