//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyDeTai.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QuanLyDeTaiEntities : DbContext
    {
        public QuanLyDeTaiEntities()
            : base("name=QuanLyDeTaiEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Administrator> Administrators { get; set; }
        public virtual DbSet<ExaminationBoard> ExaminationBoards { get; set; }
        public virtual DbSet<Group> Groups { get; set; }
        public virtual DbSet<Major> Majors { get; set; }
        public virtual DbSet<Report> Reports { get; set; }
        public virtual DbSet<SignUp> SignUps { get; set; }
        public virtual DbSet<Student> Students { get; set; }
        public virtual DbSet<Teacher_ExaminationBoard> Teacher_ExaminationBoard { get; set; }
        public virtual DbSet<Teacher> Teachers { get; set; }
        public virtual DbSet<Topic> Topics { get; set; }
    }
}
