//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyDeTai.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Report
    {
        public string reportId { get; set; }
        public string review { get; set; }
        public double result { get; set; }
        public string groupId { get; set; }
        public string examinationBoardId { get; set; }
    
        public virtual ExaminationBoard ExaminationBoard { get; set; }
        public virtual Group Group { get; set; }
    }
}
