//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyDeTai.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public string studentId { get; set; }
        public string studentName { get; set; }
        public bool gender { get; set; }
        public System.DateTime birth { get; set; }
        public string email { get; set; }
        public string phone { get; set; }
        public string address { get; set; }
        public bool lead { get; set; }
        public string groupId { get; set; }
        public string majorId { get; set; }
    
        public virtual Group Group { get; set; }
        public virtual Major Major { get; set; }
    }
}
