//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyDeTai.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Teacher
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Teacher()
        {
            this.Teacher_ExaminationBoard = new HashSet<Teacher_ExaminationBoard>();
        }
    
        public string teacherId { get; set; }
        public string teacherName { get; set; }
        public bool gender { get; set; }
        public System.DateTime birth { get; set; }
        public string email { get; set; }
        public string phone { get; set; }
        public bool lead { get; set; }
        public string degree { get; set; }
        public string topicId { get; set; }
        public string majorId { get; set; }
    
        public virtual Major Major { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Teacher_ExaminationBoard> Teacher_ExaminationBoard { get; set; }
        public virtual Topic Topic { get; set; }
    }
}
